version: "3.2"
services:
  mongo:
    image: mongo:5
    networks:
      - internal
    restart: always
    ports:
      - "27017:27017"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile-frontend
    image: tulip-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - mongo
      - api
    networks:
      - internal
    environment:
      API_SERVER_ENDPOINT: http://api:5000/
      VIRTUAL_HOST: tulip.h4xx.eu

  api:
    build:
      context: services/api
      dockerfile: Dockerfile-api
    image: tulip-api:latest
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ${TRAFFIC_DIR_HOST}:${TRAFFIC_DIR_DOCKER}:ro,z
    environment:
      TULIP_MONGO: ${TULIP_MONGO}
      TULIP_TRAFFIC_DIR: ${TRAFFIC_DIR_DOCKER}
      FLAG_REGEX: ${FLAG_REGEX}
      TICK_START: ${TICK_START}
      TICK_LENGTH: ${TICK_LENGTH}
      VM_IP: ${VM_IP}

  flagids:
    restart: on-failure
    build:
      context: services/flagids
    image: tulip-flagids:latest
    depends_on:
      - mongo
    networks:
      - internal
    environment:
      TULIP_MONGO: ${TULIP_MONGO}
      TICK_START: ${TICK_START}
      TICK_LENGTH: ${TICK_LENGTH}
      FLAGID_SCRAPE: ${FLAGID_SCRAPE}
      TEAM_ID: ${TEAM_ID}
      FLAGID_ENDPOINT: ${FLAGID_ENDPOINT}
      VISUALIZER_URL: ${VISUALIZER_URL}
      DUMP_PCAPS: ${DUMP_PCAPS}

  assembler:
    build:
      context: services/go-importer
      dockerfile: Dockerfile-assembler
    image: tulip-assembler:latest
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ${TRAFFIC_DIR_HOST}:${TRAFFIC_DIR_DOCKER}:ro,z
    # Command line flags most likely to fix a tulip issue:
    # - -http-session-tracking: enable HTTP session tracking
    # - -dir: directory to read traffic from
    # - -skipchecksum: skip checksum validation.
    # - -flush-after: i.e. 2m Not needed in pcap rotation mode
    # - -disable-converters: disable converters
    command: "./assembler -http-session-tracking -skipchecksum -dir ${TRAFFIC_DIR_DOCKER}"
    environment:
      TULIP_MONGO: ${TULIP_MONGO}
      FLAG_REGEX: ${FLAG_REGEX}
      TICK_LENGTH: ${TICK_LENGTH}
      FLAGID_SCAN: ${FLAGID_SCAN}
      FLAG_LIFETIME: ${FLAG_LIFETIME}
      PCAP_OVER_IP: ${PCAP_OVER_IP}
      DUMP_PCAPS: ${DUMP_PCAPS}
      DUMP_PCAPS_INTERVAL: ${DUMP_PCAPS_INTERVAL}
      DUMP_PCAPS_FILENAME: ${DUMP_PCAPS_FILENAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  enricher:
    build:
      context: services/go-importer
      dockerfile: Dockerfile-enricher
    image: tulip-enricher:latest
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ${TRAFFIC_DIR_HOST}:${TRAFFIC_DIR_DOCKER}:ro,z
    command: "./enricher -eve ${TRAFFIC_DIR_DOCKER}/eve.json"
    environment:
      TULIP_MONGO: ${TULIP_MONGO}

volumes:
  mongo-config:
  mongo-data:

networks:
  internal:
